### ISSUE TITLE
Bug with deleting mine

### ISSUE THREAD

**Issue by Pub4Game** [Falkirks/MineReset#10]
You did the wrong thing removing mine, /mine destroy does not remove mine from the configuration.

**Comment by Falkirks** [comment]
@Pub4Game Thanks. It's weird that this hasn't been discovered until now. The fix should be fairly easy. However, I am on a internet break and as this is non-crucial, it can wait until I get back. If you want it done before I get back (October 23rd), submit a PR and I can merge it and tag a release for you.

**Comment by Pub4Game** [comment]
Heh, I'm too lazy :D

**Comment by Pub4Game** [comment]
@Falkirks !?

**Comment by Pub4Game** [comment]
:+1:  Thanks
