### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by FlorinMF** [Falkirks/MineReset#101]
why they give me Could not queue reset for 1
what to do?

**Comment by Falkirks** [comment]
This is likely because your level is not loaded. Can you use the newest dev version on Poggit ([](https://poggit.pmmp.io/r/24907/MineReset_dev-35.phar)).

**Comment by FlorinMF** [comment]
so it does

**Comment by Falkirks** [comment]
@FlorinMF ????

**Comment by FlorinMF** [comment]
@Falkirks that's what he writes

**Comment by Falkirks** [comment]
Can you copy what it prints out over to here?

**Comment by FlorinMF** [comment]
no

**Comment by FlorinMF** [comment]
why they give me Could not queue reset for test

**Comment by Falkirks** [comment]
It gives you that error because your world isn't loaded. If you want to download the new version (linked above) and copy the debugging info, I can help you further. Otherwise, I'm closing this.
