### ISSUE TITLE
"Could not queue reset for (mine name)"

### ISSUE THREAD

**Issue by Dayne11** [falkirks/MineReset#102]
Hello, I keep getting a "Could not queue reset for (mine name)" error. My mine won't reset. Any solutions?

**Comment by Dayne11** [comment]
How do i load the level correctly?

**Comment by PluggedPointers** [comment]
Samee!! How do I fix this?

**Comment by Falkirks** [comment]
Is the level with the mine in it properly loaded? Try teleporting there and see?

**Comment by Dayne11** [comment]
How so? Want to join and see?

**Comment by Falkirks** [comment]
Can you install the latest build of MineReset on Poggit ([](https://poggit.pmmp.io/r/24907/MineReset_dev-35.phar)) and then run the command `/mine report`. It will prompt you to open a new github issue, but you can copy the data over to this thread and make a comment.
