### ISSUE TITLE
issues with /mine create

### ISSUE THREAD

**Issue by OpticRevolutionYT** [Falkirks/MineReset#106]
so i downloaded your plugin but then when i went to create a mine it would just crash my server
here is the crash dump if it helps you:
PocketMine-MP Crash Dump Tue Jul 3 02:28:44 CEST 2018

Error: Class 'pocketmine\scheduler\PluginTask' not found
File: MineReset-master/src/falkirks/minereset/Mine
Line: 20
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: MineReset v3.1.0

Code:
[11] use pocketmine\scheduler\PluginTask;
[12] 
[13] /**
[14]  * Class Mine
[15]  *
[16]  * Programmer note: Mine objects have no state. They can be generated arbitrarily from serialized data.
[17]  *
[18]  * @package falkirks\minereset\mine
[19]  */
[20] class Mine extends PluginTask implements \JsonSerializable {
[21]     private $pointA;
[22]     private $pointB;
[23]     private $level;
[24]     private $data;
[25]     private $name;
[26]     private $isResetting;
[27] 
[28]     private $resetInterval;
[29] 
[30]     private $api;

Backtrace:

PocketMine-MP version: 3.0.4+dev.1218 [Protocol 261]
Git commit: 6b2250cbcee22fcc8ae6db9c30037b8bf19b2d4b
uname -a: Linux g1 4.5.0-0.bpo.2-amd64 #1 SMP Debian 4.5.4-1~bpo8+1 (2016-05-13) x86_64
PHP Version: 7.2.4
Zend version: 3.2.0
OS : Linux, linux

Loaded plugins:
AntiInstaBreak 0.1.2 by dktapps for API(s) 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
MagicWE 0.4.0 by XenialDan for API(s) 2.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10
PiggyCustomEnchantsShop 1.1.0 by DaPigGuy for API(s) 3.0.0
PiggyCustomEnchants 1.2.0 by DaPigGuy for API(s) 3.0.0
Repair 1.0.1 by JackMD for API(s) 3.0.0
BlazinJoin 1.1.4 by iiFlamiinBlaze for API(s) 3.0.0
WorldProtect 2.3.6 by aliuly for API(s) 3.0.0
BlazinBroadcasts 1.0.3 by iiFlamiinBlaze for API(s) 3.0.0
InvSee 0.0.1 by BlockHorizons for API(s) 3.0.0
BasicHUD 1.0.7 by aliuly for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
KillMoney 1.0.0-beta by kenygamer for API(s) 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
FormAPI 1.2.0 by jojoe77777 for API(s) 3.0.0
DevTools 1.13.0 by PocketMine Team for API(s) 3.0.0
MysteryCrate 6.2.0 by JackMD, DaPigGuy for API(s) 3.0.0
PlayerInfo 2.0.3 by Matthww for API(s) 3.0.0
essentialsTP 1.2.1 by  for API(s) 3.0.0
Worlds 2.0.3 by survanetwork for API(s) 3.0.0
AntiSpamPro 1.4.1 by awzaw for API(s) 3.0.0
BlazinFly 1.8.6 by iiFlamiinBlaze for API(s) 3.0.0
MCPEToDiscord 1.3.2 by Jackthehaxk21 for API(s) 3.0.0
BankNotes 1.0.0 by AndreasHGK for API(s) 3.0.0-ALPHA12, 3.0.0
Slapper 1.4.0 by jojoe77777 for API(s) 3.0.0
TopVoter 2.4.0 by SalmonDE for API(s) 3.0.0
PureEntitiesX 0.5.0 by milk0417, RevivalPMMP for API(s) 3.0.0
BuycraftPM 0.5.1 by Tebex Limited for API(s) 3.0.0
PurePerms 1.4.2 by 64FF00 & ProjectInfinity for API(s) 3.0.0
ItemCase 1.2.2 by aliuly for API(s) 3.0.0
AdvancedKits 5.2.3 by luca28pet for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
MyPlot 1.2.6 by Wiez, Exxarion, jasonwynn10 for API(s) 3.0.0
MineReset 3.1.0 by Falk for API(s) 3.0.2, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12
EasyShop 0.0.1 by MTwinz for API(s) 3.0.2, 3.0.0, 3.0.0-ALPHA12
Heal 2.0.0 by Karanpatel567 for API(s) 3.0.0-ALPHA8, 3.0.0-ALPHA7, 3.0.0-ALPHA9, 3.0.2
VoteReward 3.0.3 by LDX for API(s) 3.0.2, 3.0.0
TimeCommander 1.0.2 by TheDeibo for API(s) 3.0.2
PowerNick 1.0.0 by McpeBooster for API(s) 3.0.2, 2.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6
RankUp 0.4.0 by Falkirks for API(s) 3.0.2, 3.0.0-ALPHA11, 3.0.0-ALPHA12

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNXAtz27aW/isYp7NtekW9/FbHO+v40aS1G63t3HSmvJOBSEhCTBIsQVpWOt3fvuccACRIO7Hr
eHs3MxmLeJ73+Q4I6Y+NUqZiYzLa3hxu7+7ujrd6G6IoVLEx+WOjXOfQtXHy4eTi4u3FRm8jFVrz
BbYdJVxr9m2uomtRpjITYaijpYirRBRhOE2qhcyuuL7+lmWqZHNVZTHMn8sEJ5/D+AuhRRmkXJei
GOgiGsx5ci2Laz3A1QrsHeA4mJXgn8l4+GdvI6eF/SWgP1KxQHJHI+iotGAPUvUDzBqNYTT+3YS/
g++/x49b8JF9zwxzdvfRNjXipx3TPS3UouBpKgpkTkxoJFOzjyIqNVvyGwHtTJe8FH12tRRrFvGM
zQRbCOAMWmPGi5ksC17IZM3mhUqZFoXkifwEfTEveR+326033jMb/1fOo2uQP3OyCsNaWOYjDt6n
wQP4OB7Cx6hmhonbUmSxZo0gmEzzRKQiA8LD8CetsktLCJ8lgv2Bi6BUGfzLC3kDxLNvciWz8hBl
OB7f2/eK+ja7fYm4EQl1bXW7kGfq2e72ZDwV1LPT7ZGaDKCU2YIG7Bp9jve6A0k+bzIwtBtu9t83
QzeH3aE8lz9sgJ2BbiKwqd/+1dswSkvQwJAWmDEl80KJBudTWOZGFFoqtMrN/rC/9Y9Y3EDrrJJJ
DI41Hu2B3RaqVJGCVcY7o94GbONGw8iFLOFpZzYebw+jWSTEeDyPoj0uduLZfrQ5HG7uzvZm89H+
bBxvzWBCwa8TOYM5w/5o3B9CS2VJO5NZdcsWI7bV3+4Pg2F/lqv+OOBpvLPFXozY5fmUHYuZBHvE
EVvB6H9gxN4/Ruy78XC0Ewy3g9HmS3a7t/NhB0nLlzmsutsfE6GfwHqIbrMpdH5Q2u0KDfSQ0EPt
qxoFd5iV8k0GHvGqEPzaE2Wnw5cl8NYfQwuvyqUqYJnfNuLrkue53viXleBvJMJhcHg2fX0I3t9r
PY/dM44XGRo0UF8WlehtxCJHTzAa1mpeHvsNKacYY7cLwzaVYXiO/RCXFEdxTN9eXr1/e3F2DE0r
MdOyRM5QAud8IaP3Jx6/rqXN6BaJ02P0V5GBEx7zzGN1TKwYlhyrjsVN+3fL/t22f3fs3137d8/+
3XfrPFk2lpGuLC6vDi+u3k3vSGIqF4v1UaVLlZ5k0ZJDvLlcqtx3qs+M8CU1ApPoSOqYw8Qfq3XX
Jp7K12fIeLzO71ngy1x2OBz/Gzh8PHcXIuey8BiyDW0ejIF6PPwEeev8+Lk4MKuFodn7ccQvyzLX
k8EAYu2ymvUjlQ7MMgPLATD3KuGfZPaTwk1qBr3GrilutZmU8jThqZQZThHPxWx71TBs6PE/P0Z3
71WRxIBdSoApHoOtZp/FcX+TAojHIgCDKnk2SzSrheEKKcgNBY8JKPfo8rySxVyKJB402C+wCWhQ
FkIMLNJscVvr/FUBu0UwQt/RvNfVNfLNf5/+G6rutjzGFt5kN5dCeMzahnZeuuPHrxKQ7mtVyE8q
08/FYWvRMDSUhOEZ8CCKxzDzimsZvX537OvONXV1tvt3GPSyip8clXgiPvIsLhSs9ZAx11yCEE4i
lal0fTh944nBa/QFsd3f7UIrlYkZ/H8uSdjlwlAYCmDNMGxR86BWf5ZJcg5rrD1+mrauXofBTJS8
zdO1yNYLmFh8BjAOO4DxaQDSF/IXJFKTHoY+Fw+K4VQVaVupruUB3PBRfVRiF/89l1KbFcPQElF/
eAwrx+LmSqnEj7F1Uye3bna5aWoudiV4+lwsuf3D0KPkr6WehrJBvQZi/zW66PoI632/APCbfaZ3
7mrQoqbes0NAB6B8Yr4WRrUYQxyc8LUo3mRz5cPfprGNNO4k03NelsvV6rk4tsvhGZCjwP/8GOsV
WguoA3mir6YeS63mrku20+cz8eLvCAG2vf/jUKDu4j/9kD50VdzwTJSA1a6fSym0poV/4IE1IX/V
An3aBnYV4BSr9sucp4D2OicOrrWtrq0u2uGrT/zZLJAWC0Mot6SG7QHumnOFhpaHcQ4BvdNkfQek
Ylubmb0udP870ekpgiCfsodPSo6mJ1fqWOpIFbEfLlvtbRY3uxgGI1G5FEt+ez0ePWeshOxgKEBy
Hl8sv+LZ9S9QabSKirrtDoJpM3MIGFBw/frHnz+DXp54vNWBK5bLZjdQnCPx8ZxeJjzPhX8u4Fq6
LvZ/DlK02fjJ6ayhaOB4AAavVP5PEInPYd3Ujpx3WLzkSaqy45MvMjiH+P1YDt2CYehIaD496oSq
KsQJRJ5SCv2rn5xb7e1KcLvLVSqT6+HWCMupC3Ejb3gyPT+fPpcSC7NknqZ5GOZAl7B0QdL2qPzL
WM0jddBmF921WkcFn5fTc99fm8auRDrZ4krMxC07kynsHj9bbWy3B75rmAke6ogyb8MeqfOpKFLd
0bdp6zppJ67ubJ2eDofsP/DFF77jAsQkM1k+Gxz9YDYwuiWKvI9PcGGaa8vlZh089ShFesR169zD
NXWh2/jvOCgAFtIIds/F42PtYQxgJxLxz7J1WtVqbhf74y6YS6qIj/dyUX4dPy0Luv9k21WHXqbx
6HxykK4ZGLTYtoZ+tORlx86p6Q7cG91n539JJp4I7ornlEcl7KYNvPsVYo+q9PQkcO0bn3EBJLb5
9AwOQMtQTTpNVNmqRqmha/sd6Pheik/QcnJ7ywsc1Nv4yLXKVussGw2/0oRaZ0I2xtmjkZO6spni
C7Pjk39K2t6r6oh8rGMtGw+8hWouDXgi8C4S+C9y77xpOuVJt/IZtw+MdtuPe+3H/c7p0sOnT08M
LvdeDvDZfDDEnHC97ryeq5seOCE+v1rJ7NPn5PRcLDpqHh81X4vWK3x67Ja8HYX/zAue5bwUyfbO
7v0gfO+LBrBfv6V9IptIJWjxkSwiALwQK94qoLzG7kWFTlI4O/71s2p7Iv2wZBg2FDw53MM6AZZe
A48bBOUyFUcqTXkWt5F5q71bZ3US+9VSHAs5U3d4fyLPrc0f/XpcrUTxi4yuW7dMXNsDleJ5lItX
SuHx2z0KHN/1u+32486T3yQ7ChGdNsR+UbvlSpZAqHlp5xGO75ah7nznxxzb8MBdiVMb7r4cm782
vH4pUbUwgKtggPYK4lPNwwPui/dlIN6kAoRB+/UHrWtG/XzJSb1aFCCOfl4oKE2pCJpsvJjWT+xI
ATpfMLxpFxZh9uKqEuynKmGbbDiejHcn25vs6OTyio2Hoz0ckKoyPpgWEhI6M2szUNGSRQTlmHBX
BGCo6Q5yVZQHo/3R1pDmi1QV6yDBuudge7x3/gpbV0tgDBp1eaDmc2zhWaYqQGpBTqeuAY+WUtyY
q2cHKqP1c77KAvsiGPR9MNqhHfitnaQPRrQnTxK1CuaJXCzL1lyeyRTwQqstVTPXgC+DUhWLA1pl
rgogp26zdIKY40gV9XN+k9vZsZzPZVQl5fpgRKuZ23yqCOwtNH2AzXTLLUATtmJtGrUQsTcGr1ce
HJ+cHr47u8JWY43B75Uo1nZP21SA8TmC8HM/51qvVBEffE//QCRVqQLNb4Tj3ehK5geLcX+Z4mNf
VNijMrxPGRDPf3gPf2LnjRSrIAa1Iag+IAO5nanbAP3NrowXv+rXkv11mqABMoxzLCLbq0AooD0y
QQZCZi1DBpPEO5FaMCc1xgvByqVg4E4aPvAS70vitdGZYDKLkioWMXxgd0wf17pUKcyc4wLdNTWf
ix5T0FNocwUTr2+xtaoKZ+pyzoB3OZe0A+i9ANODygwW/kWs6uUGsZhz0LxmK5V9WzI8F+IFQ6Gn
wGwEBrlGCsul1Ibv1VJkrMoXBY9hgX6YoUrMYpMwYy+uloUABxEYDFnCs0WF9zrxJiuJzKpPS3hO
VEQXMlGoOPVoKSLLRXsiyNwlT5H1V/Ja5iKWvK+KxQCfBmeg2A9q/uHN5dsPO5v7wfgDzgMx1gtN
WAhBcRFu4EbvlwJlx0oF9GQxAy6ZLguSbwkBTid0l5W6SZpEKdABn0RJKo2h6IkEgxASJ6TkFBY2
jtdsSYdf0K6XVRkrdFlzzRiJuTQrR4nSIjZkHaL3M4wtQAmz78XZjeTsv9FzYAh5kHtjPmEY3HEi
IMYV42ilWgE1dhejKm4XYpUGI4REAIZA3EHAh5GQbWKUU9MRAFkzIKpZ/oR81a0DHDOMIwzMFSwC
SZ2tmbUjGG49u+5txPDivQRBg2euGY9jBgDeWB6SCbZ2DeRwDSkHQycDe5sJlAcIXfxe8QTVsZA3
MPaGJxD7v7NbQsB/CYub/SCiCAzjAWhzsRDFBHpx51+qdAbSBnc61OssohvC+FYFHKiP/e9ACWSf
jkkctSwgM1ZgEjBa9xi9znFXncFkeyCGFKSmMYWTWCDvYVtaZeA5OITWviSTAX7AuQp1C4EckPca
2SFTz2rSUKqGnDdz9FAcgp7YY7L8FiRXFjQrFphGyAo7c9l3wAHeEx+jRIiHwHI5oZU6xk/phhVV
lqEWY4zdKifp0x1f3WfH4sZ+ZikmJRYVXC97fsCx1ojSKIoqL02rERYKBbKoMEyRUsHKQELgdcbB
+I2SMdB8PwFoG2hpCmQMRtVvzAvGBmaMs1OXsSkK/ZioGZgMQh1mmhklcoxlqVjw2boEUbNLI+Qh
iVVqXNnEMCB0JUnkZEYM07IFBLZJE3NzCeRBAAbKM1pqDtHP7WgMG9RUkTsuFGhIodOjNcA+CyLS
IIwJG4YUBCnflBBEefz/nHwEhF8gHvHGVxEPMC2n/R16c/TY1TSDYIF4AeKnpQb3dCSNhuMtQxW5
/HvyA0uc/vbrySNPIHowPgCshBSbQYpl4lZEFYVwZeg1LogpuR4tbiOATLphh4LU26uTCbt6/eaS
nb05f3MFIXp69ubkkk1PLhhg659PLnoMBrGrtzDqhL1//fbshE0v3gLuvex3PL4li/H2jhEFoHmp
CHNgwNXIXERZ10qiDqojkDrkkxgDCY0I8P6DCaeUq1UGLEIYBhNCVj9nYcayADUnlMYx3phhIaEq
XANCbBOunS+zF28xTyCMoeH9u4PRAmydA+rKRYRox4gUaTX6NHNrBsCoRK4bNjeHlk/98l6CLNeb
husFL2bgCkGkksQgeQw290qVPAtJsXOYnQMBGiroinCVTwVgzgrs7mXPBf6O4VnLM8lzPqcv5ODy
aeNxffbWBHZj4oA6VJXENSUS8sQqYw3t6MMsJ9KBw53h0DDJXpxSVLiTAclYzOyaK/qKj00xONf2
B74lekoFLqzuurZwjwH5xnDp4C+qqIBN0OaszcZVmhsgZgCpbQ+w3ejnGEfY0UQxkefohifI3ODR
/B6RQiaGfGa++yS1roQ2VaQWCwecMSzhXg1JPac4k/ctPkbSaODnpIP1YLSssmttyD7iObbJtEoh
beKxC3MVDOqNmdrRENAIE93CSpAc4645QcmQEzG0WYBIvoI0umVVdKxMR9d0EeVgRDNr41DnJGYd
O8xjiEBAEEFFLCxLx0ABgQ4AgCgvIMogBbMEfg1MYJWEMwxjDVMwjSRomHCb4tAaqoLMEqxf7Jpf
WuZL9hZm9tJNXdGALyUGIM54CQU+4nOiFXAPWIvNGRSyTL1me02qmIkaKlKueuErxfVgqCzWJa7d
Y8HI0xfqirYNSkeKDekYhxsISsU34r/Y8Iy1DcFznAuNlqY+ew1QDgzngLAZO5q+68FcoGAGTrSS
MZg3pXyKiPXyAS0/YbsWLzdIWpNgvKF9dhjH+IXBZD6A2teA+1iAudqNYEuG50ZoT5671SnMW8sr
H05uMVohPORJz4RC3Pi9zKC4ArYgtgiKUgiB302zqQPQTSmLtQFOolNbrGOzPLCP7VLl3Pqdlp9E
rWEE2k6x+ArHwSEA4sZevPy5tT82k1722dTOSXixoAncVtTWOnDDecEXyBroCcvkPCFEgiVoCpSj
t/MCdXeUSPpSI5b9BRRGQpfs/OodEaqBIeR5VpX07VRSb7ObqRb6NtKkZRXgpAnRikYfi1m1MCav
bGZlCK8Kcn0La7DuwRSFX5nr170aZWTKgWXel5lEMkakTzfCBID3vMgwq3sz8UTD5nFcxS4AMRTQ
BSqwGZnyNX6vk0MCAoKgbsGv+GIoBBWmFBZhZQcJcDvQaxbIeWDbmpIWwvp/shEWVhZrYgVN/Lvq
WZtjD+Gq6tD614TYsjWxZgP8NmwFUWCwiIy/4AG5ri0pzEyUnpgDDgWFNTqnq8CEK60pkuOXRZnm
NzZZ4KmXO1XErpp8vGsH8U/w0ggVuDH3bBzqpzoRPIjAl86FMKVYpqJE5oxmgimdc/wCLzpLqm5c
1Y0pjmRnziJdj9nOK7bcwV/r6Ee4cwBGGinNoRcNtcZeaXsuEYHDlxQN7ZTATJmwHCR4IxNC7i3n
xQNbSEd2OQoqhOmAVwwiJQaS8dBiMEyQBtqhwPAQEdstnnNybDXXYHloQ7SBAzOuhbfZdyOIm/fs
0mNj6Bjd1yHKqP+SYrgWPhVkSFe4Mh5A2ZNgJiBrmf1QfUZYdNTXnAHGLouiWxPwT1Z8rc3adh3P
Ak2mtNnA+bcVpq2tMpR90kUZPTeqdXp674klVfiHqaowKs5NOrdBEk3R8oZSQSLxvAaMGj8S7mAv
LgiEeFPJcjJhTglmwiw1E3MMaXT+TfBh6XwH3YVOxVtoxnCO2zjOIa4z3iUT2IgoNzfCb1M4vJdE
XuC3/+mEjdwXCLVTrZINJZsYOvDwJKhycGPRqIZFiFaM2vDYz4tPx7TRDL9BpCmWoxRNoAM7hISX
MssWM8dMDhbRFJ9l9iIA03zBFlCv6kYozTmWk0v/rmBsCFxxSfUsZBsTk2d4JpNXifVg+xlBAg2x
eWUPdyN3CHITAdHhMKpNmCs3yAXNmd3EuB0eL1JpbVoNuLAaAiLqI6AmmqNlB3jg226pY1OrFdKL
zOaq0QFEpMCcLrtxS4WqICL6eFOvLxWRmqlsnWJxiDEfT2kjXdOM1a7tZk030U5RnS8WhVjYc8P6
RBbRNX4j/7rDGNEGbvr2+O0E5GDzl8UMGBBWwpQkHFxkRRtqIrumnpr63vsMQCi1vI0dkka6sgQV
mt5JnT9tAmxANrUqT2BQqdDPQHgHeD2ISfmS9xh+e4kQTemgLOSluSigOAkwumSYUk2nTczmMJC3
jgPti1IvYVcA2QH6UIByocCuh6o23W6Hrm4Ni75yAUnUecymaVwRhztEibrEQIi7EdSxc9xBdr9e
3nb46zshfhEG2GBs1GnM3ztGcsf7pSyNIN2B0dK2UUSg15ym5rAhAU/aoZSLCXnLeb0O1GvAhcFf
GGE84ETL2eDnEj5PJOQvI6GTW44/r2EeEDsBfVZFE6cr6gIbxWO8CfuNwAxkrR6d6/0LVzTfj3DQ
wX/JRRwguC7wPREdo7h3kgQ+78tAhHAoLWqqLagcB71IINRiBo902pUIoE8M32BioKdk1Ow2Yadn
h1eT8Q+7ve3921Fv83azN/5h9EMMqd1Ez+/we4sRxs2DvaEJsuZpa/ulgX/mZY13imH8GLMFiNYe
JhIMo9NA0FW0xtdRVVRWhQu3rqor6vcwFFZgHUg+ESFn7WQVuDdEYAEE91+cUjyhnWh4a42Kcr5p
+eC1BAQ6+/Wpp8ptHQCxTdtaOLrG0klT8QfimEkoW9bmhITGIbcSf2AiMfmBnMSwSKsDqCjqULzR
26AfctF0h3Dyx8YRJHvvVzpi+sZZ/QiKz7ROvJY8ao3XvwM1YtP/nQ/z6yLucRYBuFx6DfiWL4t5
4TfZ3wqqn6vC3/KjtrdXduj6xlwmdJm+7p+X/u+MLFL/aQkJxtx8QWIBW8V0xanuv5yeeU/pzLyi
9JvWwCL9con9xLbx4toY346wAG9CbA+3hrvw8Zs3eMa3Nxd8vDUf723tzvnu9mh/OBzNxOb+MNrf
42LIIz4Xm3u77BuSZVb6jE6XJJaxvYGSKy1vfdHbU0d7xXDX/FTMhZjbkyNfLctU+WLQlKS0r2ht
72vig1zMZMaLtd0c7/iU6lpkADF8Qa85vbB39H2SufnC5TY9knxkPfzPP/8X6PzDLQ==
===END CRASH DUMP===

**Comment by Falkirks** [comment]
I am unable to test right now due to issues with my MCPE client. But I believe this should be fixed in 68c1c703673807553283c8f200c4f017ed2b1de2.
