### ISSUE TITLE
Disappearing

### ISSUE THREAD

**Issue by InstaGamer** [Falkirks/MineReset#18]
I have found a bug in which were you reset a mine all nearby signs or sometimes all signs in the world where you reset the mine will disappear and when a player is in the mine and you reset it the player will become invisible and Sometimes when i use the command /mine reset mine1 the plugin will be disabled in the server for the plugin work again i need to restart the server.. Please fix this bug. LEET need it to be fix and other servers too.

**Comment by Falkirks** [comment]
This is a duplicate of #12 and you have provided no details on the plugin being disabled.

**Comment by InstaGamer** [comment]
Why do signs disappear when we rest the mines?

**Comment by Falkirks** [comment]
Because chunks are created from scratch and thus lose their entities. This was explained in #12
