### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by Mike4l6** [Falkirks/MineReset#19]
API is wrong the one I'm using is 2.0.0

[15:13:47] [Server thread/ERROR]: Could not load plugin 'MineReset': Incompatible API version
(I've named the phar MineReset)

**Comment by Falkirks** [comment]
This plugin doesn't support `2.0.0`.

**Comment by MichaelM04** [comment]
!? I guess you never plan to do any work to this plugin ever again but you can simply just change the api to support PHP7 I can make a pull request if needed

**Comment by Falkirks** [comment]
Yes, but the plugin doesn't function correctly on newer APIs and is very complicated to update. I may work on this plugin again, but this is not an issue, the plugin isn't intended to support `2.0.0` in it's current state.

**Comment by MichaelM04** [comment]
The issues may vary per build ImagicalMine,Clearsky,etc 
I use official PocketMine-MP PHP7 Build all that was done was the api I tested the functionality setting the mines and reseting works flawless no errors in console so far.

**Comment by Vaivez66** [comment]
I just changed the API to 2.0.0 and it was working fine for me... (I'm using PocketMine)

**Comment by Mike4l6** [comment]
me too
