### ISSUE TITLE
mines are not reloaded correctly

### ISSUE THREAD

**Issue by gamerzezze** [Falkirks/MineReset#2]
it worked at first but after I restart the server it gives me this message 14:39:39 [NOTICE] InvalidArgumentException: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in phar://D:/san andreas/PocketMine-MP/plugins/MineReset_v2.0.3.phar/src/minereset/MineReset.php on line 177 and defined" (E_RECOVERABLE_ERROR) in "/MineReset_v2.0.3.phar/src/minereset/Mine" at line 13
and after that it stopped working I redownloaded it but it did not help

**Comment by Falkirks** [comment]
That means the level is no longer loaded, there should be a better error though.

**Comment by WazzyWaffles** [comment]
I need help ASAP people cant destroy my mine blocks dont know y please help I just doent let them

**Comment by WazzyWaffles** [comment]
On mcpe

**Comment by Falkirks** [comment]
@WazzyWaffles I have a busy life to keep up with. I will get to this when I have time. I understand that it is important to you and will strive to get it done.

**Comment by WazzyWaffles** [comment]
I have a server to run I just need help please :( and how long will it take
PS its not my fault yall only have one staff and you the one that put
urself in a situation that you cant handle in future reference u have to do
it right....ThankYou ill be waiting
And how old r u  just wondering if ur younger missing scool for this crap ,
but ok bye

**Comment by Falkirks** [comment]
@WazzyWaffles I tested your issue on a clean installation of the latest dev build and could not reproduce.

**Comment by WazzyWaffles** [comment]
Wat does that mean

**Comment by WazzyWaffles** [comment]
And how do u set reset time on minereset

**Comment by iVertx** [comment]
that happens after you restart the server...

set up a mine, reset it, will work, ok...
but when you try to reboot your server this error will ocurr and the plugin will not load anymore...
it's happening on latest pm builds, and really broke my server, (i'm porting then from 0.10.5) :/

**Comment by Falkirks** [comment]
@iVertx Thanks.

**Comment by iVertx** [comment]
ok, I found the fix by myself
These issue is related to the level name present on ./world/level.dat not matching with the name of the world folder, The plugin saves the name present on leve.dat on their config.yml intead of saving the name of the folder, so, these issue happens...

the fix that i found for this issue is deleting the original ./level.dat from the world that yor mine are located, and restarting the server, pocketmine will regenerate this file with the correct name by itself if your world are properly documented on pocketmine.yml, and the plugin will load fine.

**Comment by Infernus101** [comment]
[CODE]
pocketmine.yml
worlds:
world1: []
[/CODE]
In your pocketmine.yml file, search for these world tag and replace 'world1' with your world name where your mines are built! Bet this will work, worked for me! This will automatically load your world on startup!
