### ISSUE TITLE
Help fast

### ISSUE THREAD

**Issue by andrew33212** [Falkirks/MineReset#20]
I need help with the mine reset plugin it was working fine then it just stop when I type in the command /mine nothing comes up not even it saying this is not a command I run a prison sever and I need to know how to fix this or even restart the plugin and I'll have to do the mines over again I don't care as long as I can get this plugin to work help  get me it andymcpe99@hotmail.com

**Comment by Falkirks** [comment]
Are there any errors shown in the console?

**Comment by andrew33212** [comment]
Em I'm not sure I'll go look and show i

**Comment by andrew33212** [comment]
You*

**Comment by andrew33212** [comment]
Their is one error I just seen but I think it's for killmoney says error: "call to a member function getDamager() on null" what dose that mean

**Comment by Falkirks** [comment]
Can you upload the entire `console.log` from the session and any error files generated? I need to know where that error is generated

**Comment by andrew33212** [comment]
[Image]
Like this

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 1:59 PM -0700, "Falkirks" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you upload the entire console.log from the session and any error files generated? I need to know where that error is generated

-

**Comment by Falkirks** [comment]
The image didn't attach correctly

**Comment by andrew33212** [comment]
Also have u ever used the plugin Slapper before ? Saying there's a error with that I'm not sure if it just with me or if it's happening to other people

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 2:00 PM -0700, "Andrew Martin" <andymcpe99@hotmail.com<mailto:andymcpe99@hotmail.com>> wrote:

[Image]
Like this

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 1:59 PM -0700, "Falkirks" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you upload the entire console.log from the session and any error files generated? I need to know where that error is generated

-

**Comment by andrew33212** [comment]
Wait what do u mean

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 2:01 PM -0700, "Falkirks" <notifications@github.com<mailto:notifications@github.com>> wrote:


The image didn't attach correctly

-

**Comment by andrew33212** [comment]
[Image]
There's a fresh one
Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 2:06 PM -0700, "Andrew Martin" <andymcpe99@hotmail.com<mailto:andymcpe99@hotmail.com>> wrote:

Wait what do u mean

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 2:01 PM -0700, "Falkirks" <notifications@github.com<mailto:notifications@github.com>> wrote:


The image didn't attach correctly

-

**Comment by Falkirks** [comment]
The images won't appear on GitHub.

**Comment by andrew33212** [comment]
Have you got Skype or kik or email I email u thought we were talking on emails

**Comment by Falkirks** [comment]
@andrew33212 I would prefer if you attached the stuff to the issue here on GitHub, but if you can't, you can email me at `me@falkirks.com` and I will do it for you.

**Comment by andrew33212** [comment]
Em I'm new to this website and I'm not really sure how to work this so I'll just email u it and hopeful u can help me out
