### ISSUE TITLE
MineReset Error

### ISSUE THREAD

**Issue by FocusedSG** [Falkirks/MineReset#21]
I kept on getting this error I don't know why. The mines are at my default world, so it is surely loaded.

[Server thread/CRITICAL]: TypeError: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in phar://C:/Users/user/Desktop/Genisys/plugins/MineReset.phar/src/minereset/MineReset.php on line 184" (EXCEPTION) in "/MineReset.phar/src/minereset/Mine" at line 13

**Comment by Falkirks** [comment]
Does your world folder name match the name in the `level.dat`?
