### ISSUE TITLE
Help my mine reset plugin stop working

### ISSUE THREAD

**Issue by andrew33212** [Falkirks/MineReset#22]
My mine reset plugin has stop I ran a prison sever and I need help ASAP I delete the mines in the mine reset yml and it was working then when I reset the sever it just has stop working there's no errors in the console and when I type /mine nothing comes up not even this isn't a command

**Comment by Falkirks** [comment]
That's really strange. Are you sure there are no errors in the console? Nothing that says failed to load?

**Comment by andrew33212** [comment]
I am sure this is what I did 1 i wiped my prison map cos I was updating it and cos the mine where still in the yml file with the same ranks I wanted to use I had to delete the so I went onto the yml file and delete all the mine then I went back into my sever and it work until I restarted my sever then the command just stop working nothing come up I type in /mine and nothing comes up I have went on console and even type in mine reset A and nothing comes up like I never even type anything .. I have wiped my sever fully so it would wipe everything tho the same thing it works until u make a mine then restart and it just stops

**Comment by andrew33212** [comment]
???

**Comment by Falkirks** [comment]
@andrew33212 PocketMine version?

**Comment by andrew33212** [comment]
Help plzz

**Comment by lewislovesreuben** [comment]
Same here when plugin loads console says - 29.06 07:17:01 [Server] Server thread/CRITICAL TypeError: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in phar:///plugins/MineReset_v2.1.phar/src/minereset/MineReset.php on line 182" (EXCEPTION) in "/MineReset_v2.1.phar/src/minereset/Mine" at line 13

**Comment by lewislovesreuben** [comment]
If i delete config files it works for about a hour or so then stops

**Comment by Dog2puppy** [comment]
Levels aren't loaded on startup for the crashing issue, and manually deleting mines in the config.yml, is somehow messing up the plugin.

**Comment by andrew33212** [comment]
@lewslovesreuben that's the same that's happening to me also what dose this mean

**Comment by andrew33212** [comment]
Well I can't add pics when I do /plugins my mine reset plugin is red

**Comment by andrew33212** [comment]
I need it to be fixed my sever been close for over a week now

**Comment by Infernus101** [comment]
[CODE]
# pocketmine.yml
worlds:
   world1: []
[/CODE]
In your pocketmine.yml file, search for these world tag and replace 'world1' with your world name where your mines are built! Bet this will work, worked for me! This will automatically load your world on startup!

**Comment by andrew33212** [comment]
Ok I'll try

**Comment by andrew33212** [comment]
No it's already the name of the world

**Comment by andrew33212** [comment]
@dog2puppy yes that what is happened also I've wiped the full sever and still not working after I restart the sever

**Comment by StringerJ** [comment]
when plugin loads console says - 30.06 07:19:01 [Server] Server thread/CRITICAL TypeError: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in phar:///plugins/MineReset_v2.1.phar/src/minereset/MineReset.php on line 182" (EXCEPTION) in "/MineReset_v2.1.phar/src/minereset/Mine" at line 13

**Comment by StringerJ** [comment]
@Infernus101 I cant find where that is on my pocketmine.yml im on genisys btw

**Comment by andrew33212** [comment]
So what has happened to me has happened to a lot of people so it's a BUG NEEDS TO BE FIXTED

**Comment by lewislovesreuben** [comment]
While i to want this plugin to be sorted keep in mind the plugin developer has probably seen this and is doing what he can. Also 0.15.0 adds more features so im sure its a pain for developers..

**Comment by andrew33212** [comment]
This happened to me on 0.14

**Comment by lewislovesreuben** [comment]
Read what i just said again im sure the developer is working on it geez

**Comment by Dog2puppy** [comment]
@Falkirks Will this all be fixed? For the unloaded world, instead of it crashing, just reload the plugin each time a world is loaded like TapToDo does. And then, the plugin stops working when the config is changed manually.
