### ISSUE TITLE
MineReset 2.1 is Completely broken Crucial Error

### ISSUE THREAD

**Issue by LinuxLogo** [Falkirks/MineReset#24]
"Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in phar:///plugins/MineReset_v2.1.phar/src/minereset/MineReset.php on line 182" (EXCEPTION) in "/MineReset_v2.1.phar/src/minereset/Mine" at line 13

**Comment by Chris-Prime** [comment]
Because world has different folder name than actual in level.dat, correct that yourself. Plugin works fine.

**Comment by LinuxLogo** [comment]
._.
