### ISSUE TITLE
Issue with multiple worlds

### ISSUE THREAD

**Issue by Falkirks** [Falkirks/MineReset#25]

**Comment by KillerXtream** [comment]
I think I have a fix for this.

**Comment by Falkirks** [comment]
@KillerXtream Care to share?

**Comment by Vaivez66** [comment]
I may haven't experienced it yet. What's the issue, anyway?

**Comment by Falkirks** [comment]
It's unclear, some people have told me that mines in other worlds will not save correctly.

**Comment by Vaivez66** [comment]
It works just fine for me. Can someone confirm this issue?
