### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by MagicPandaDev** [Falkirks/MineReset#28]
29.11 11:27:14 [Server] Server thread/CRITICAL Error: "Cannot call constructor" (EXCEPTION) in "/phar_MineReset-master_I4NXPpOncts6Jzr.phar/src/minereset/MineResetTask" at line 20
29.11 11:27:14 [Server] Server thread/CRITICAL Unhandled exception executing command 'mine reset jj' in mine: Cannot call constructor

**Comment by Falkirks** [comment]
That's a weird error. What version of PM are you running?

**Comment by Falkirks** [comment]
I should be able to remove line 20 safely. It does nothing.

**Comment by MagicPandaDev** [comment]
0.16.0.5
