### ISSUE TITLE
Generic chunk to binary

### ISSUE THREAD

**Issue by Infernus102** [Falkirks/MineReset#31]
![untitled](https://cloud.githubusercontent.com/assets/22660649/21564196/bfa2c480-ceb0-11e6-8e8f-d53ebfef9229.png)

**Comment by alexbgameson** [comment]
I get the same error. 


31.12 07:28:40 [Server] INFO 06:28:40 | Elywing thread:CRITICAL > Error: "Call to undefined method pocketmine\level\format\generic\GenericChunk::toBinary()" (EXCEPTION) in "/MineReset_v2.1.phar/src/minereset/Mine" at line 45
