### ISSUE TITLE
error on plugin load

### ISSUE THREAD

**Issue by kabluinc** [Falkirks/MineReset#34]
[Server thread/CRITICAL]: TypeError: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in C:\Users\server\Desktop\New folder\plugins\MineReset-master\src\minereset\MineReset.php on line 188" (EXCEPTION) in "/plugins/MineReset-master/src/minereset/Mine" at line 13

**Comment by Lazerplayz** [comment]
Are you using a different software then pmmp this happens when the plugin doesn't load when using blue light Elywing ect

**Comment by kabluinc** [comment]
Only using PMMP. When the world is loaded from pocketmine.yml this error doesn't happen.

**Comment by Falkirks** [comment]
Worlds can only really be loaded from the `pocketmine.yml` or they won't be available in time for `MineReset`. There are many duplicates of this issue.
