### ISSUE TITLE
Plugin has stopped working on Tesseract, Elywing, and Bluelight

### ISSUE THREAD

**Issue by alexbgameson** [Falkirks/MineReset#39]
Plugin has stopped working on Tesseract, Elywing, and Bluelight server software.

**Comment by Falkirks** [comment]
I don't support those server softwares. Can you provide the error?

**Comment by Lazerplayz** [comment]
17.03 03:49:35 [Server] INFO [03:49:35] critical> TypeError: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in /plugins/MineReset-master/src/minereset/MineReset.php on line 200" (EXCEPTION) in "/MineReset-master/src/minereset/Mine" at line 20

**Comment by Lazerplayz** [comment]
I tested with all softwares seem to use this issue beside pmmp!

**Comment by Falkirks** [comment]
I think it might have to do with the plugin load order, but I can't confirm as I don't have any of those servers installed.

**Comment by Lazerplayz** [comment]
It's a major bug that needs to be fixed ASAP I'll try look into it, I think those softwares have different world loading

**Comment by Falkirks** [comment]
I can rewrite things to be more like SimpleWarp, which is like an hour or less of dev time. But I have reset my computer, so it will take me several hours to setup everything again.

**Comment by Lazerplayz** [comment]
It's okay :)

**Comment by Lazerplayz** [comment]
@Falkirks this issue can be fixed on spoons do this but for your mines https://forums.pmmp.io/threads/how-to-load-worlds-on-startup-with-pmmp.1577/#post-17280
