### ISSUE TITLE
MineReset not working

### ISSUE THREAD

**Issue by Bublz654** [Falkirks/MineReset#4]
i start up the server, make a mine and then people mine from it, I reset the mine a couple of times then the plugin stops working. None of the commands work and no errors show up in the console. Is it possible you can fix this ?

**Comment by Falkirks** [comment]
What version of PocketMine-MP are you running?

**Comment by HellBublz** [comment]
PocketMine-MP version 1.5dev-1198

**Comment by Falkirks** [comment]
That isn't supported yet.

**Comment by qwefqwfqwefqwef** [comment]
PLEASE UPDATE

**Comment by qwefqwfqwefqwef** [comment]
@Falkirks please update plugins!

**Comment by kennethgomad02** [comment]
yes its true

**Comment by qwefqwfqwefqwef** [comment]
@Falkirks How soon can you update the plugin?) It is very useful, I would like to be corrected!

**Comment by kennethgomad02** [comment]
soon he trying to fix the pocketmine use /level/LevelChunks auto recovery

**Comment by Falkirks** [comment]
@qwefqwfqwefqwef This issue hasn't been reproduced and I won't be able to fix it until I reproduce it. I have the level issue on my work list though.

**Comment by kennethgomad02** [comment]
ok could you teach me how to make changing blocks to air automatically pls
