### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by XFizzer** [Falkirks/MineReset#40]
16.02 09:51:54 [Server] CRITICAL Could not execute asynchronous task MineResetTask: Task crashed
16.02 09:51:54 [Server] CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::fromBinary()" (EXCEPTION) in "/MineResett.phar/src/minereset/MineResetTask" at line 39

**Comment by RTGDaCoder** [comment]
I have this same issue..

**Comment by XFizzer** [comment]
@RTGDaCoder if you look at my fork I got it to work

**Comment by Falkirks** [comment]
@XFizzer I looked at your fork and it seems your change isn't substantial, only a revert. If you could explain how it fixes your issue, I will merge it.

**Comment by Falkirks** [comment]
Oh. I think I understand what is going on. The issue was fixed in ec8f118caeaf0771d9993cf5ff5c0359783081d4 which has not yet been included in a release. Are you using the code from GitHub or the latest release?

**Comment by XFizzer** [comment]
From GitHub

**Comment by Falkirks** [comment]
Are you entirely sure? Look at line 39 in  `/plugins/MineReset/src/minereset/MineResetTask.php`. It should look exactly like https://github.com/Falkirks/MineReset/blob/ec8f118caeaf0771d9993cf5ff5c0359783081d4/src/minereset/MineResetTask.php#L39.

**Comment by Falkirks** [comment]
Oh, I notice you have it in a `phar` file. Please try cloning directly from GitHub and using DevTools to load it.
