### ISSUE TITLE
Erro in console

### ISSUE THREAD

**Issue by iLeoDev** [Falkirks/MineReset#41]
[Server thread/CRITICAL]: TypeError: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in C:\Users\server\Desktop\New folder\plugins\MineReset-master\src\minereset\MineReset.php on line 188" (EXCEPTION) in "/plugins/MineReset-master/src/minereset/Mine" at line 13

Hi my mame is Leo, You can help me to resolve This ? In Your plugin .

**Comment by Falkirks** [comment]
This has been reported many times. See #34.

**Comment by iLeoDev** [comment]
Oh :c
