### ISSUE TITLE
Non well formed numeric value 

### ISSUE THREAD

**Issue by ExaSonit** [Falkirks/MineReset#42]
A non well formed numeric value encountered in C:\Users\User\Downloads\PocketMine-MP-master\PocketMine-MP\plugins\MineReset\src\minereset\MineResetTask.php on line 58

		
        for ($x = $this->a->getX(); $x <= $this->b->getX(); $x++) {
            for ($y = $this->a->getY(); $y <= $this->b->getY(); $y++) {
                for ($z = $this->a->getZ(); $z <= $this->b->getZ(); $z++) {
                    $a = rand(0, end($sum));                                                        error is in this line
                    for ($l = 0; $l < count($sum); $l++) {
                        if ($a <= $sum[$l]) {
                            $hash = Level::chunkHash($x >> 4, $z >> 4);
                            if(isset($chunks[$hash])){
                                $chunks[$hash]->setBlock($x & 0x0f, $y & 0x7f, $z & 0x0f, $id[$l][0] & 0xff, $id[$l][1] & 0xff);

This is string, why I have this problem?

**Comment by Falkirks** [comment]
@ExaSonit Did you figure this out?
