### ISSUE TITLE
Plugin stops load without error shown

### ISSUE THREAD

**Issue by MCPEGamerJPatGitHub** [Falkirks/MineReset#43]
The plugin sometimes do not load (it is stopped then started) on pmmp as well as other forks such as Bluelight and Tesseract.

**Comment by MCPEGamerJPatGitHub** [comment]
It has been a issue some earlier versions. It shows no error or crashdump, so there isn't a way to show what the problem is.

**Comment by Lazerplayz** [comment]
Please use PMMP to fix this issue this plugin doesn't support spoons

**Comment by MCPEGamerJPatGitHub** [comment]
@Lazerplayz I said above that I also tested on pmmp.
