### ISSUE TITLE
Mine reset error

### ISSUE THREAD

**Issue by kabluinc** [Falkirks/MineReset#46]
This error is showing when ever I do /mine reset {mine}

`Notice: A non well formed numeric value encountered in C:\Users\Gamer27832 server\Desktop\New folder\plugins\MineReset-master\src\minereset\MineResetTask.php on line 63
`

**Comment by Falkirks** [comment]
Link for ref https://github.com/Falkirks/MineReset/blob/master/src/minereset/MineResetTask.php#L63
