### ISSUE TITLE
Error on Pocketmine

### ISSUE THREAD

**Issue by DoseOfNone** [Falkirks/MineReset#48]
[Server thread/CRITICAL]: TypeError: "Argument 5 passed to minereset\Mine::__construct() must be of the type array, boolean given, called in /home/servers/Prison/plugins/~MineReset/src/minereset/MineReset.php on line 198" (EXCEPTION) in "/~MineReset/src/minereset/Mine" at line 13

**Comment by mal0ne-23** [comment]
that means your world isn't loaded before it tried to load a mine.

**Comment by DoseOfNone** [comment]
No it isnt, my worlds are running as its my default main map. .-. IDK.

**Comment by XDqrkneZ** [comment]
Same broo

**Comment by Falkirks** [comment]
@XDqrkneZ You has a different error...

**Comment by Falkirks** [comment]
I think this error is occurring because you closed your server before setting your mine. Could that be the case?

**Comment by DoseOfNone** [comment]
No, when my staff build its me creating the mines. Ive had this config for awhile and upon updating my PocketMine-MP version, it began processing this error.

**Comment by Falkirks** [comment]
Yes, that is somewhat expected for this issue, as the enforcement of type became strict in newer versions. So one of your mines could not be set properly, and it has gone unnoticed until now. Either way, the issue needs to be fixed.

**Comment by XDqrkneZ** [comment]
yep because I' about to open a prison server and I need this awesome plugin @Falkirks

**Comment by Falkirks** [comment]
This may have been fixed in #47
