### ISSUE TITLE
Error with /mine reset

### ISSUE THREAD

**Issue by XDqrkneZ** [Falkirks/MineReset#51]
I tried to /mine reset a and i got this error

An unknown error occurred while attempting to perform this command
[Tesseract] [13:17:43] CRITICAL> Unhandled exception executing command 'mine reset s' in mine: Cannot call constructor

**Comment by Falkirks** [comment]
Is any additional information provided?

**Comment by WastelandCoyote** [comment]
I've had this issue also. Console is returning this.

05.04 17:06:58 [Server] INFO [Tesseract] [20:06:58] CRITICAL> Error: "Cannot call constructor" (EXCEPTION) in "myzip:///MineReset-master.zip#MineReset-master/src/minereset/MineResetTask" at line 33

**Comment by XDqrkneZ** [comment]
CHANGE SERVER SOFTWARE @WastelandCoyote

**Comment by WastelandCoyote** [comment]
What?

**Comment by WastelandCoyote** [comment]
The entire server is server software.

**Comment by XDqrkneZ** [comment]
what software are you using? Tesseract, PMMP etc.
