### ISSUE TITLE
Error ;-;

### ISSUE THREAD

**Issue by XDqrkneZ** [Falkirks/MineReset#52]
CRITICAL> Unhandled exception executing command 'mate reset a' in mate: Cannot call constructor
[Tesseract] [19:02:59] CRITICAL> Error: "Cannot call constructor" (EXCEPTION) in "/MineReset-master/src/minereset/MineResetTask" at line 33

**Comment by WastelandCoyote** [comment]
Lol you already opened an issue for this, bud xD

**Comment by XDqrkneZ** [comment]
oh ;-;

**Comment by WastelandCoyote** [comment]
:3

**Comment by XDqrkneZ** [comment]
YO MATE IF U R HAVING ISSUES WITH THIS MAKE SURE TO USE DIFFERENT SOFTWARE LIKE BLUELIGHT CUZ I WAS USING TESSERACT AND ITS THE REASON WHY I GET ERRORS!!!! :ddddddddddd
