### ISSUE TITLE
Error calling constructor

### ISSUE THREAD

**Issue by WastelandCoyote** [Falkirks/MineReset#54]
The issues keep being closed by the OP without any answers being given, and new ones keep being opened that provide no information whatsoever. 

I feel bad for opening an issue because the other guy is pretty much spamming somewhat related issues and it ends up not addressing any issue whatsoever. 

Console is returning the error 05.04 17:06:58 [Server] INFO [Tesseract] [20:06:58] CRITICAL> Error: "Cannot call constructor" (EXCEPTION) in "myzip:///MineReset-master.zip#MineReset-master/src/minereset/MineResetTask" at line 33

It sounds like it may be an issue with Tesseract, I've debated repairing it myself but I've got other plugins that I need to update, and I figured since you're active that it would be better to have the plugin updated. 

The plugin runs, it allows me to create and set mines, however, it runs into an issue when trying to reset the mine, and returns that error.

**Comment by Falkirks** [comment]
Possible fix in 24d2b4d4d70e89d1583f791846604e05a02a18ac

**Comment by ZaneWalter** [comment]
I am having the same error please help.

**Comment by Falkirks** [comment]
@ZaneWalter Are you running with 24d2b4d?

**Comment by WastelandCoyote** [comment]
Hey, sorry for the delay. 

I installed 24d2b4d and it is still returning the same error in console when attempting to reset the mine.

**Comment by ZaneWalter** [comment]
@Falkirks Thank You. Problem is solved. It works like a charm. Awesome plugin!!

**Comment by Falkirks** [comment]
@WastelandCoyote That makes very little sense. I will have to test it.
