### ISSUE TITLE
mine reset error

### ISSUE THREAD

**Issue by XDqrkneZ** [Falkirks/MineReset#60]
I did /mine reset a and i got unknown error occured, here is what the console said

CRITICAL> Unhandled exception executing command 'mate reset a' in mate: Cannot call constructor
[Tesseract] [21:14:09] CRITICAL> Error: "Cannot call constructor" (EXCEPTION) in "/MineReset-master/src/minereset/MineResetTask" at line 33

mm

**Comment by Lazerplayz** [comment]
MineReset is a powerful mine management tool for PocketMine-MP. We do not support Tesseract or any other 'spoons'

**Comment by Lazerplayz** [comment]
if you tested on pmmp and this happens tell me.

**Comment by XDqrkneZ** [comment]
Oh. I have quite a but of issues with PMMP but I will try it.

**Comment by Lazerplayz** [comment]
The plugin works fine as it should be on PMMP are you using the latest commit?

**Comment by XDqrkneZ** [comment]
@Lazerplayz /: they still haven't updated to 1.0.6 which makes people want to use Tesseract like me

**Comment by Lazerplayz** [comment]
Pmmp is perfectly fine no big issues unlike tesseract you should use pmmp

**Comment by XDqrkneZ** [comment]
@Lazerplayz oh yeah, have they updated to 1.0.6 yet?
