### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Ben420x** [Falkirks/MineReset#62]
Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\scheduler\ServerScheduler::scheduleAsyncTask() must be an instance of pocketmine\scheduler\AsyncTask, null given, called in phar:///plugins/MineReset_v2.4.phar/src/minereset/Mine.php on line 74" (EXCEPTION) in "/src/pocketmine/scheduler/ServerScheduler" at line 78
15.04 10:44:32 [Server] Server thread/CRITICAL Unhandled exception executing command 'mine reset starter' in mine: Argument 1 passed to pocketmine\scheduler\ServerScheduler::scheduleAsyncTask() must be an instance of pocketmine\scheduler\AsyncTask, null given, called in phar:///plugins/MineReset_v2.4.phar/src/minereset/Mine.php on line 74
15.04 10:44:32 [Server] Server thread/INFO An unknown error occurred while attempting to perform this command
15.04 10:44:32 [Server] INFO Notice: Undefined variable: mineResetTask in phar:///plugins/MineReset_v2.4.phar/src/minereset/Mine.php on line 74
15.04 10:43:28 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\scheduler\ServerScheduler::scheduleAsyncTask() must be an instance of pocketmine\scheduler\AsyncTask, null given, called in phar:///plugins/MineReset_v2.4.phar/src/minereset/Mine.php on line 74" (EXCEPTION) in "/src/pocketmine/scheduler/ServerScheduler" at line 78
15.04 10:43:28 [Server] Server thread/CRITICAL Unhandled exception executing command 'mine reset starter' in mine: Argument 1 passed to pocketmine\scheduler\ServerScheduler::scheduleAsyncTask() must be an instance of pocketmine\scheduler\AsyncTask, null given, called in phar:///plugins/MineReset_v2.4.phar/src/minereset/Mine.php on line 74

**Comment by SleepSpace9** [comment]
https://github.com/Falkirks/MineReset/commit/6f03cb00c230a905a87fa2e7eaa8bee804b01bb6#diff-07e750a59aa94ab4b1ed06b5fbecda42R74 😉
