### ISSUE TITLE
Mine Problem

### ISSUE THREAD

**Issue by XxParkerGamesxX** [Falkirks/MineReset#67]
when I create a mine like /mine create A 
then I do the positions then I do /mine set 1 50 13 50
then I do /mine reset A 
and its says "Could not queue reset for A."
please help me

**Comment by Falkirks** [comment]
Because you never set the mine properly. Try running

```
/mine create A
/mine set A 1 50 13 50
/mine reset A
```

**Comment by XxParkerGamesxX** [comment]
Could you tell me how to do it

**Comment by Falkirks** [comment]
Run those commands in order on yer server....
