### ISSUE TITLE
Bug with blocks

### ISSUE THREAD

**Issue by Pub4Game** [Falkirks/MineReset#7]
Make mine out of wood 17, then reset after a few blocks stop falling out and when they put the torch they disappear. 
I'm sorry, I translated in Google translator

**Comment by Falkirks** [comment]
This might be a PocketMine or MCPE issue. I will need to investigate further.

**Comment by Pub4Game** [comment]
When do you plan to fix this bug?

**Comment by Falkirks** [comment]
@Pub4Game It might not be possible to fix, I need to reproduce and debt it first.

**Comment by Pub4Game** [comment]
Nothing has changed ((((

**Comment by Pub4Game** [comment]
@Falkirks Yay!)))))) PM 0.12.1 №35 no bug :D
