### ISSUE TITLE
Command problems 

### ISSUE THREAD

**Issue by XFizzer** [Falkirks/MineReset#72]
Error: Declaration of falkirks\minereset\command\MineCommand::execute(pocketmine\command\CommandSender $sender, $commandLabel, array $args) must be compatible with pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, string $commandLabel, array $args)
File: MineReset.phar/src/falkirks/minereset/command/MineCommand

Yes i am using the latest pmmp build

**Comment by NickTehUnicorn** [comment]
Shouldn't you update all the commands to the new format?

**Comment by Falkirks** [comment]
@NickTehUnicorn There is only one command, the rest are SubCommand classes which is a MineReset supertype that doesn't have strict typing enforced yet. Strict typing should be implemented soon, but isn't needed for the plugin to run in this case.
