### ISSUE TITLE
Multi World Support

### ISSUE THREAD

**Issue by ObeyBeastJj23** [Falkirks/MineReset#75]
Will we be getting any multi world support for MineReset? its just that i need it a bit to set up some plugins i'm writing.

**Comment by Falkirks** [comment]
MineReset has supported multiple worlds for ages. Is there an issue?

**Comment by RedstoneAlmeida** [comment]
I think he meant for the mine worlds to be loaded before the mine was loaded on itself, because if the world is not loaded the error plugin

**Comment by Falkirks** [comment]
@RedstoneAlmeida This is no longer the case. You will get an info notice if the world isn't loaded and the mine will work automatically when the world does load.
