### ISSUE TITLE
Conflictpe

### ISSUE THREAD

**Issue by AyyItzJ4y** [Falkirks/MineReset#77]
Hey falkirks, So ive seen the /mine reset for conflict pe that it had a timer "USAge" and did they code that or Theres a newest version of minereset

**Comment by AyyItzJ4y** [comment]
And this is not an issue sorry

**Comment by Falkirks** [comment]
The newest version does have the ability to reset mines on a timer. You must configure it yourself in the YAML file though.

**Comment by AyyItzJ4y** [comment]
Where could I download it

**Comment by Falkirks** [comment]
https://github.com/Falkirks/MineReset/releases/tag/v3.0.2
