### ISSUE TITLE
Bug with reset other cunks

### ISSUE THREAD

**Issue by zKoz210** [Falkirks/MineReset#83]
![image](https://user-images.githubusercontent.com/28255085/31160771-9de53052-a8db-11e7-9532-c0989b5ff331.png)

PM-MP: https://github.com/pmmp/PocketMine-MP/commit/c273a465378f0cb0f1e2b14578ac9e2661530624

I think the blame @dktapps
MineReset: https://github.com/Falkirks/MineReset/commit/997abc3a00b7c4bafcd4bc619f2cee2810782b1d

Old build work nice:
![image](https://user-images.githubusercontent.com/28255085/31160796-d8c471ba-a8db-11e7-9057-2cae4bc6ba09.png)

MineReset: https://github.com/Falkirks/MineReset/commit/7297ab4fba875c8f83c4fdfa506339eb14bc0ff5

**Comment by dktapps** [comment]
Not entirely sure what could have caused this... I'll take a look later.

**Comment by dktapps** [comment]
For reference, the commit range: https://github.com/Falkirks/MineReset/compare/7297ab4fba875c8f83c4fdfa506339eb14bc0ff5...master

**Comment by zKoz210** [comment]
@dktapps You can fix it or revert changes?

**Comment by dktapps** [comment]
I haven't had the time to investigate this... sorry...

**Comment by dktapps** [comment]
I can't reproduce this bug, do you have any other information?

**Comment by dktapps** [comment]
does #91 resolve the issue?

**Comment by zKoz210** [comment]
Yes, thanks, but now chunks are not sent to player. You will need a tap more times on block to update chunks.

1) Make area with more blocks
2) /mine reset-all
3) player gets new chunk, but when you break block drop will be completely different.

**Comment by dktapps** [comment]
Sounds like https://github.com/pmmp/PocketMine-MP/issues/1813

**Comment by zKoz210** [comment]
Hmm... I use https://github.com/pmmp/PocketMine-MP/commit/d93ded90471d078a535862e2be3c0388a2558884

It's already fixed, right?

**Comment by dktapps** [comment]
If it was, the issue wouldn't still be open. That's only a partial fix for the issue.

**Comment by zKoz210** [comment]
`unset($this->chunkCache[$index]);` is already there in the function `$this->unloadChunk()`, why remove it twice?

`unset($this->chunkCache[$index]);` need only if `$unload = false`

**Comment by dktapps** [comment]
Please test with https://github.com/pmmp/PocketMine-MP/pull/1823

**Comment by zKoz210** [comment]
@dktapps yes, it fixed bug, thanks <3
