### ISSUE TITLE
Bugggg when mines try to reset

### ISSUE THREAD

**Issue by HipsterAF** [Falkirks/MineReset#85]
Asynchronous Worker #2 thread/DEBUG #3 (): pocketmine\scheduler\AsyncTask->run()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #2 src/pocketmine/scheduler/AsyncTask(67): falkirks\minereset\task\ResetTask->onRun()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #1 MineReset-master/src/falkirks/minereset/task/ResetTask(74): spl_autoload_call(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #0 (): BaseClassLoader->loadClass(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/CRITICAL ParseError: "syntax error, unexpected end of file" (EXCEPTION) in "src/pocketmine/level/Level" at line 2991
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #3 (): pocketmine\scheduler\AsyncTask->run()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #2 src/pocketmine/scheduler/AsyncTask(67): falkirks\minereset\task\ResetTask->onRun()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #1 MineReset-master/src/falkirks/minereset/task/ResetTask(74): spl_autoload_call(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #0 (): BaseClassLoader->loadClass(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/CRITICAL ParseError: "syntax error, unexpected end of file" (EXCEPTION) in "src/pocketmine/level/Level" at line 2991
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #3 (): pocketmine\scheduler\AsyncTask->run()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #2 src/pocketmine/scheduler/AsyncTask(67): falkirks\minereset\task\ResetTask->onRun()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #1 MineReset-master/src/falkirks/minereset/task/ResetTask(74): spl_autoload_call(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #0 (): BaseClassLoader->loadClass(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/CRITICAL ParseError: "syntax error, unexpected end of file" (EXCEPTION) in "src/pocketmine/level/Level" at line 2991
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #3 (): pocketmine\scheduler\AsyncTask->run()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #2 src/pocketmine/scheduler/AsyncTask(67): falkirks\minereset\task\ResetTask->onRun()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #1 MineReset-master/src/falkirks/minereset/task/ResetTask(74): spl_autoload_call(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #0 (): BaseClassLoader->loadClass(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/CRITICAL ParseError: "syntax error, unexpected end of file" (EXCEPTION) in "src/pocketmine/level/Level" at line 2991
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #3 (): pocketmine\scheduler\AsyncTask->run()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #2 src/pocketmine/scheduler/AsyncTask(67): falkirks\minereset\task\ResetTask->onRun()
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #1 MineReset-master/src/falkirks/minereset/task/ResetTask(74): spl_autoload_call(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/DEBUG #0 (): BaseClassLoader->loadClass(string pocketmine\level\Level)
07.10 12:56:18 [Server] Asynchronous Worker #2 thread/CRITICAL ParseError: "syntax error, unexpected end of file" (EXCEPTION) in "src/pocketmine/level/Level" at line 2991

Can't reproduce, happens randomly
Using 7297ab4

**Comment by Falkirks** [comment]
It seems like it is trying to include Level.php on the worker thread and failing with "Asynchronous Worker #2 thread/CRITICAL ParseError: "syntax error, unexpected end of file" (EXCEPTION) in "src/pocketmine/level/Level" at line 2991".

**Comment by HipsterAF** [comment]
Yea

**Comment by David-AI** [comment]
fixed?

**Comment by Falkirks** [comment]
I have no idea where this could have come from because it's a parser error. If I ever reproduce this locally, I will reopen this.
