### ISSUE TITLE
Teleport players to warp on reset

### ISSUE THREAD

**Issue by XDqrkneZ** [falkirks/MineReset#86]
mine resets
players get teleported not above the mines but sometimes bottom, outside mine or even random places

**Comment by Falkirks** [comment]
I am using getSafeSpawn(), so this seems like expected behaviour. But obviously not good.

**Comment by XDqrkneZ** [comment]
oh okay,  you know what's a decent idea? add /mine setwarp <mine name> so players will be teleported to that warp everytime the mine reset

**Comment by Falkirks** [comment]
Yes, this has been requested before. It is a good idea.
