### ISSUE TITLE
Blocks are not going where they should

### ISSUE THREAD

**Issue by EpicPinkCreeper** [Falkirks/MineReset#89]
The blocks are not being placed in the correct places.  I tried it multiple times but it always goes in the same wrong spot.  
![screenshot_2017-11-01-23-13-01](https://user-images.githubusercontent.com/28110073/32309711-85ddce1a-bf5b-11e7-9435-7e3697e9d3ff.png)

**Comment by Falkirks** [comment]
Did it work before? Do you have any way to check whether the data in the mines.yml is just has the wrong coordinates (ie: they were saved badly)?

Maybe related to #83 ?

**Comment by EpicPinkCreeper** [comment]
I teleported to each of the coordinates in the mines.yml file and they are where I set them, not where the blocks actually are.  The size doesn't match. The structure I built is a square of 21 blocks and the snow chunk loaded by the plugin is a square of 16 blocks. The y coordinates are correct though.

**Comment by dktapps** [comment]
Reproduced and PR'd a bugfix.
