### ISSUE TITLE
Mine Permissions!

### ISSUE THREAD

**Issue by optimusprime338** [Falkirks/MineReset#94]
I love this awesome plugin! Thanks for creating it but would like to recommend a feature if you can add then that will be awesome:-
Each mine having its own permission set so a player having permission to that mine can only break blocks there! example: for mine a permission can be mine.a or whatever!

**Comment by Falkirks** [comment]
I would suggest using an area protection plugin to accomplish this. I don't think it makes sense as a MineReset feature.
